openapi: 3.0.0
info:
  title: vive-api
  version: '1.0'
  description: Vive Rest API
  contact:
    name: Vive Lead
servers:
  - url: 'http://localhost:3000'
paths:
  /api/v1/hsa/reimbursements/requests:
    post:
      summary: Submit an HSA request
      tags: []
      responses:
        '200':
          description: Success response
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/CommonResponse'
              examples:
                ok-response:
                  value:
                    dateTime: '2019-08-24T14:15:22Z'
                    transactionId: c59cdf30-426c-40fa-a1b5-fc3cb7a59ca0
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                invalid-request:
                  value:
                    dateTime: '2019-08-24T14:15:22Z'
                    transactionId: 75906707-8c31-479c-b354-aa805c4cefbc
                    error: Bad request
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                internal-error:
                  value:
                    dateTime: '2019-08-24T14:15:22Z'
                    transactionId: 75906707-8c31-479c-b354-aa805c4cefbc
                    error: Internal server error
      operationId: postHSAReimbursementRequest
      description: Submit an HSA reimbusment request
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                amount:
                  type: number
                reason:
                  type: string
                attachment:
                  type: string
                  format: binary
                bankName:
                  type: string
                bankRoutingNumber:
                  type: string
                bankAccountNumber:
                  type: string
              required:
                - amount
                - reason
                - attachment
                - bankName
                - bankRoutingNumber
                - bankAccountNumber
            examples:
              valid-request:
                value:
                  amount: 500
                  reason: Need that money
                  attachment: abcdef
                  bankName: Chase
                  bankRoutingNumber: '610061'
                  bankAccountNumber: '123456789'
              invalid-request:
                value:
                  amount: 0
                  reason: Need that money
                  attachment: a
                  bankName: Chase
                  bankRoutingNumber: '610061'
                  bankAccountNumber: '123456789'
        description: The request body
  '/api/v1/user/{id}/activation/password':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    post:
      summary: Set a new password
      tags: []
      responses:
        '200':
          description: Success response
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/CommonResponse'
                  - type: object
                    properties:
                      data:
                        type: object
                        properties:
                          next_step:
                            type: string
              examples:
                ok-response:
                  value:
                    dateTime: '2019-08-24T14:15:22Z'
                    transactionId: 75906707-8c31-479c-b354-aa805c4cefbc
                    data:
                      next_step: verify_identity
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                bad-request:
                  value:
                    dateTime: '2019-08-24T14:15:22Z'
                    transactionId: 75906707-8c31-479c-b354-aa805c4cefbc
                    error: Bad request
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                internal-error:
                  value:
                    dateTime: '2019-08-24T14:15:22Z'
                    transactionId: 75906707-8c31-479c-b354-aa805c4cefbc
                    error: Internal server error
      operationId: set_new_password
      description: Complete the first activation form
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                birth_date:
                  type: string
                  format: date
                last_four_digits:
                  type: string
                password:
                  type: string
                password_repeat:
                  type: string
              required:
                - birth_date
                - last_four_digits
                - password
                - password_repeat
  '/api/v1/users/{id}/activation/status':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: Get the activation status
      tags: []
      responses:
        '200':
          description: Success response
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/CommonResponse'
                  - type: object
                    properties:
                      data:
                        type: object
                        properties:
                          step:
                            type: string
                            enum:
                              - set_password
                              - verify_identity
                              - sign_docs
                          set_password:
                            type: object
                            properties:
                              birth_date:
                                type: string
                                format: date
                              last_four_digits:
                                type: string
                                pattern: '^[0-9]+'
                                minLength: 4
                                maxLength: 4
                          verify_identity:
                            type: object
                            properties:
                              first_name:
                                type: string
                              middle_name:
                                type: string
                              last_name:
                                type: string
                              address_line1:
                                type: string
                              address_line2:
                                type: string
                              city:
                                type: string
                              state:
                                type: string
                              zip_code:
                                type: string
                              phone:
                                type: string
                              mother_maiden_name:
                                type: string
                              gov_id_type:
                                type: string
                              gov_id_issue_date:
                                type: string
                                format: date
                              gov_id_expiry_date:
                                type: string
                                format: date
                          sign_docs:
                            type: object
              examples:
                ok-response:
                  value:
                    dateTime: '2019-08-24T14:15:22Z'
                    transactionId: 75906707-8c31-479c-b354-aa805c4cefbc
                    data:
                      next_step: verify_identity
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                bad-request:
                  value:
                    dateTime: '2019-08-24T14:15:22Z'
                    transactionId: 75906707-8c31-479c-b354-aa805c4cefbc
                    error: Bad request
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                internal-error:
                  value:
                    dateTime: '2019-08-24T14:15:22Z'
                    transactionId: 75906707-8c31-479c-b354-aa805c4cefbc
                    error: Internal server error
      operationId: get-api-v1-users-id-activation-status
      description: Get the activation status
components:
  schemas:
    CommonResponse:
      type: object
      description: A common object for successful responses
      x-examples: {}
      x-tags:
        - hsa
      properties:
        dateTime:
          type: string
          minLength: 1
          format: date-time
        transactionId:
          type: string
          minLength: 1
          format: uuid
      required:
        - dateTime
        - transactionId
    ErrorResponse:
      title: ErrorResponse
      allOf:
        - $ref: '#/components/schemas/CommonResponse'
        - type: object
          properties:
            code:
              type: string
            error:
              type: string
          required:
            - error
      description: A common object for error responses
  responses: {}
